language: generic
sudo: required
services:
  - docker # install a copy of docker in the container

before_install:
  - docker build -t hiro0404/react-docker -f Dockerfile.dev . # tags will only be used inside the travis process

script:
  - docker run -e CI=true hiro0404/react-docker npm run test -- --coverage # make sure npm run test exits

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: "react-docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-394445482437"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
